# Generated by Django 3.2 on 2022-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, verbose_name='Скидка'),
        ),
    ]
