# Generated by Django 3.2 on 2022-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_books_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Скидка'),
        ),
    ]
